# Generated by Django 3.1.7 on 2021-03-08 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20210308_1611'),
    ]

    operations = [
        migrations.AddField(
            model_name='snippet',
            name='copies',
            field=models.IntegerField(default=1),
        ),
    ]
