# Generated by Django 3.1.7 on 2021-03-08 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_snippet_copies'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snippet',
            name='copies',
            field=models.IntegerField(default=0),
        ),
    ]
