# Generated by Django 3.1.7 on 2021-03-09 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20210308_1750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='picture',
            field=models.ImageField(blank=True, default='/media/media/default_profile/', null=True, upload_to='media'),
        ),
    ]
