# Generated by Django 3.1.7 on 2021-03-09 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20210309_1930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='picture',
            field=models.ImageField(default='media/media/iconfinder_moon_dark_mode_night_5402400.png', upload_to='media'),
        ),
    ]
